version: '3.8'

services:
  meeting-room-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=http://14.103.250.95:13000
    volumes:
      - ./app:/app
    restart: unless-stopped